# Generated by Django 5.2.8 on 2025-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.CharField(blank=True, max_length=255)),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('dropoff_address', models.CharField(blank=True, max_length=255)),
                ('start_coords', models.JSONField(blank=True, null=True)),
                ('pickup_coords', models.JSONField(blank=True, null=True)),
                ('dropoff_coords', models.JSONField(blank=True, null=True)),
                ('route_geojson', models.JSONField(blank=True, null=True)),
                ('current_cycle_hours', models.FloatField(default=0.0)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
